# -*- coding: utf-8 -*-
"""pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ECO3-MOaLpaQSGa7oNEULonvRtrFrq3e
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# New section"""

df = pd.read_csv("realistic_sales_dataset.csv", parse_dates=["order_date"])

df.head()

df.columns= (
    df.columns
    .str.strip ()
    .str.lower ()
    .str.replace (" ", "_")
)

df.shape

num_cols=['quantity','price','discount','sales']
df[num_cols]= df[num_cols]. fillna(df[num_cols].median())

cat_cols = ['product','category','city','payment_mode']
df[cat_cols]=df[cat_cols]. fillna("Unknown")

df.shape

df.info()

df.describe()

df['month']= df['order_date'].dt.month

df['year']= df['order_date'].dt.year

df['revenue']= df['quantity'] * df['price'] *(1-df['discount'])

monthly_sales=(
    df.groupby(['year','month'],as_index= False)
    .agg(total_revenue= ('revenue','sum'))
)

plt.figure()

plt.plot(monthly_sales['month'], monthly_sales['total_revenue'])
plt.xlabel('Month')
plt.ylabel('Total Revenue')
plt.title('Monthly Revenue Trend')
plt.show()

category_sales=(
    df.groupby(['category'],as_index= False)
    .agg(total_revenue= ('revenue','sum'))
)

plt.figure()
plt.bar(category_sales['category'], category_sales['total_revenue'])
plt.xlabel('Category')
plt.ylabel('Revenue')
plt.title('Revenue by category')
plt.xticks(rotation=45)
plt.show()

top_products=(
    df.groupby(['product'],as_index= False)
    .agg(total_revenue= ('revenue','sum'))
    .sort_values('total_revenue',ascending= False)
    .head(10)
)

plt.figure()
plt.barh(top_products['product'], top_products['total_revenue'])
plt.xlabel('Revenue')
plt.ylabel('Product')
plt.title('Top 10 Products by Revenue')
plt.gca().invert_yaxis()
plt.show()

city_sales=(

            df.groupby('city',as_index= False)
    .agg(total_revenue= ('revenue','sum'))
    .sort_values('total_revenue',ascending= False)
)

plt.figure()
plt.bar(city_sales['city'], city_sales['total_revenue'])
plt.ylabel('Revenue')
plt.title('Revenue by City')
plt.xticks(rotation=90)
plt.show()

plt.figure()
plt.scatter(df['quantity'], df['revenue'])
plt.xlabel('discount')
plt.ylabel('Revenue')
plt.title('discount vs revenue')
plt.show()

kpis={
    'total_revenue':df['revenue'].sum(),
    'total_orders':df['order_id'].nunique(),
    'average order value':df.groupby('order_id')['revenue'].sum().mean(),
    'top category': category_sales.iloc[0] ['category']

}